               location /purge_proxy_cache {
                        allow 127.0.0.1;
                        deny all;

                        content_by_lua_block {
                                local cjson = require "cjson.safe"
                                local purge = require "proxy_cache_purge"

                                local cache_key = ngx.var.arg_cache_key
                                local res, err, meta = purge.purge_sliced_cache(
                                        "/tmp/nginx/cache",	-- proxy_cache_path
                                        cache_key,
                                        "2",            	-- proxy_cache_path levels="2",
                                        10 * 1024 * 1024
                                )

                                ngx.header.content_type = "application/json"

                                if not res then
                                        ngx.status = 404
                                        ngx.say(cjson.encode({
                                                ok = false,
                                                error = err,
                                                meta = meta,
                                        }))
                                        return
                                end

                                ngx.say(cjson.encode({
                                        ok = true,
                                        result = res,
                                }))
                        }
                }
